import { buildDotLottie } from './dotlottie';
import { dotLottieLayout } from './strip';
import { zipStore } from './zip';
import { easingToBezier, initialState, machineOf, RUNTIME_SETTER } from '../core/stateMachine';
import { easingLabel } from '../core/easing';
import type { LottieOptions } from './lottie';
import type { InputType, Project, SmInput } from '../core/types';

/**
 * The runtime adapter (§15): Blooby's configuration → `@lottiefiles/dotlottie-react-native`.
 *
 *   Blooby State Editor → this file → .lottie + Mascot.tsx → DotLottie → inputs → states
 *
 * The generated component is *data-driven*, which is the point: it reads the input
 * definitions out of `blooby.machine.json` and picks the setter from each input's declared
 * type. No input name is ever written into the runtime — add `isListening` in the editor
 * and it works with no code change here or in the app.
 *
 * Method names are taken from the installed package's own typings
 * (`@lottiefiles/dotlottie-react-native@0.12.x`, `Dotlottie` ref type), not from docs:
 * note `stateMachineFire` — not `stateMachineFireEvent`, which is the web player's name.
 */

const SETTER: Record<InputType, string> = {
  Boolean: 'stateMachineSetBooleanInput',
  Numeric: 'stateMachineSetNumericInput',
  String: 'stateMachineSetStringInput',
  Event: 'stateMachineFire',
};

const TS_TYPE: Record<InputType, string> = {
  Boolean: 'boolean', Numeric: 'number', String: 'string', Event: 'never',
};

/**
 * The §14 export document — the whole machine in Blooby's own vocabulary, next to the
 * `.lottie` that carries the dotLottie one. Nothing here is proprietary invention: it is
 * the same data, spelled for a human reading a diff, and `core/stateMachine.ts` converts
 * between the two deterministically in both directions.
 */
export function machineConfig(project: Project) {
  const m = machineOf(project);
  const { animationOf, strip } = dotLottieLayout(project);
  const nameOf = (id: string) => project.timelines.find((t) => t.id === id)?.name ?? '';

  return {
    stateMachine: {
      id: m.id,
      initialState: initialState(project).name,
      inputs: m.inputs.map((i) => ({
        name: i.name,
        type: i.type,
        ...(i.type === 'Event' ? {} : { default: i.value }),
        ...(i.description ? { description: i.description } : {}),
        runtime: RUNTIME_SETTER[i.type],
      })),
      states: project.timelines.map((tl) => ({
        name: tl.name,
        animation: animationOf.get(tl.id),
        /**
         * The marker naming this state's frames. Every baked state shares one composition
         * so a Tweened transition has real frames to scrub through (see strip.ts); the
         * player finds them by this name, and `frames` is here only to read.
         */
        ...(strip?.segments.get(tl.id)
          ? { segment: strip.segments.get(tl.id)!.marker, frames: strip.segments.get(tl.id)!.range }
          : {}),
        loop: tl.loop,
        /** the blend used when this state is entered any way other than a transition */
        enterMs: tl.transitionMs ?? 300,
      })),
      transitions: m.transitions
        .filter((t) => nameOf(t.from) && nameOf(t.to))
        .map((t) => ({
          from: nameOf(t.from),
          to: nameOf(t.to),
          logic: t.logic ?? 'AND',
          conditions: t.conditions.map((c) => ({ input: c.input, operator: c.operator, value: c.value })),
          duration: +((t.durationMs ?? 0) / 1000).toFixed(4),
          easing: easingLabel(t.easing ?? { type: 'preset', name: 'easeInOut' }),
          easingBezier: easingToBezier(t.easing ?? { type: 'preset', name: 'easeInOut' }),
        })),
    },
  };
}

/** `{ isTyping: boolean; energy: number; mood: string }` — the app-facing prop, typed
 *  from what was actually configured rather than a loose Record. */
function inputsType(inputs: SmInput[]): string {
  const settable = inputs.filter((i) => i.type !== 'Event');
  if (!settable.length) return 'Record<string, never>';
  return `{\n${settable.map((i) => `  /** ${i.description || `${i.type} input`} · default ${JSON.stringify(i.value)} */\n  ${safeKey(i.name)}?: ${TS_TYPE[i.type]};`).join('\n')}\n}`;
}

const IDENT = /^[A-Za-z_$][A-Za-z0-9_$]*$/;
const safeKey = (n: string) => (IDENT.test(n) ? n : JSON.stringify(n));

export function mascotSource(project: Project): string {
  const m = machineOf(project);
  const settable = m.inputs.filter((i) => i.type !== 'Event');
  const events = m.inputs.filter((i) => i.type === 'Event');
  const cfgId = JSON.stringify(m.id);

  return `/**
 * Generated by Blooby — do not hand-edit; re-export from the State Editor instead.
 *
 * The state machine decides which animation plays. The app only ever sets inputs:
 *
 *     <Mascot inputs={{ ${settable.slice(0, 3).map((i) => `${safeKey(i.name)}: ${JSON.stringify(i.value)}`).join(', ') || '/* none configured *\\/'} }} />
 *
 * There is no play('watching') and no frame arithmetic here on purpose — a state entered
 * by a transition is the machine's decision, and reaching around it desynchronises the
 * two. Inputs in, state changes out.
 */
import { useEffect, useImperativeHandle, useMemo, useRef, forwardRef } from 'react';
import type { ViewStyle } from 'react-native';
import { DotLottie } from '@lottiefiles/dotlottie-react-native';
import machine from './blooby.machine.json';

export type MascotInputs = ${inputsType(m.inputs)};

export type MascotStateChange = {
  previousState: string;
  currentState: string;
  /** the configured transition that fired, when the change came from one */
  transition?: (typeof machine)['stateMachine']['transitions'][number];
};

export type MascotHandle = {
  /** fire an Event input — the one input kind that is a pulse, not a value */
  fire: (name: ${events.length ? events.map((e) => JSON.stringify(e.name)).join(' | ') : 'string'}) => void;
  /** escape hatch: the raw DotLottie ref, for anything this API does not cover */
  player: React.MutableRefObject<any>;
};

/** input name → the setter its declared type maps to. Built from the config, so a new
 *  input added in Blooby needs no change here. */
const SETTERS: Record<string, 'stateMachineSetBooleanInput' | 'stateMachineSetNumericInput' | 'stateMachineSetStringInput'> = {
${settable.map((i) => `  ${JSON.stringify(i.name)}: '${SETTER[i.type]}',`).join('\n') || '  // no settable inputs configured'}
};

export type MascotProps = {
  inputs?: MascotInputs;
  onStateChange?: (change: MascotStateChange) => void;
  /** false holds the current pose without burning frames — for off-screen copies */
  playing?: boolean;
  style?: ViewStyle;
  source?: any;
};

export const Mascot = forwardRef<MascotHandle, MascotProps>(function Mascot(
  { inputs, onStateChange, playing = true, style, source = require('./${fileBase(project)}.lottie') },
  ref,
) {
  const player = useRef<any>(null);
  const ready = useRef(false);
  // the latest values, so they can be replayed once the machine is actually running —
  // a set before stateMachineStart() is dropped by the runtime, which looks exactly like
  // "the mascot ignores my first render"
  const pending = useRef<MascotInputs>({});

  useImperativeHandle(ref, () => ({
    fire: (name: string) => player.current?.stateMachineFire(name),
    player,
  }), []);

  const apply = (values: MascotInputs) => {
    const p = player.current;
    if (!p) return;
    for (const [name, value] of Object.entries(values)) {
      if (value === undefined) continue;
      const setter = SETTERS[name];
      // an input the editor never declared has no correct setter to guess at
      if (!setter) { console.warn(\`[Mascot] "\${name}" is not an input of state machine \${${cfgId}}\`); continue; }
      p[setter](name, value as never);
    }
  };

  useEffect(() => {
    pending.current = { ...pending.current, ...inputs };
    if (ready.current) apply(inputs ?? {});
  }, [inputs]);

  const transitions = useMemo(() => machine.stateMachine.transitions, []);

  /**
   * Freeze, not pause — and never play().
   *
   * The machine owns the playhead: entering a state applies that state's \`segment\` as a
   * marker, which is what keeps playback inside one pose of a composition that holds
   * them all. play() restarts the loaded animation from frame 0 and drops the marker, so
   * the mascot runs every pose end to end. freeze() only stops the render loop.
   */
  useEffect(() => {
    if (playing) player.current?.unfreeze();
    else player.current?.freeze();
  }, [playing]);

  return (
    <DotLottie
      ref={player}
      source={source}
      style={style ?? { width: '100%', height: '100%' }}
      stateMachineId={${cfgId}}
      onLoad={() => {
        /**
         * Loaded here rather than left to the stateMachineId prop: that setter runs when
         * the prop lands, which on first mount is before the view has built its
         * animation, so its load is a no-op on nil and is never retried.
         *
         * The return value is checked because it is the ONLY report of failure. The
         * engine's parser is all-or-nothing — one mistyped field discards the whole
         * machine — and the native bindings drop this bool, so a machine that never
         * loaded raises nothing at all: the animation simply autoplays end to end and
         * looks roughly right. Silence here is not success.
         */
        const loaded = player.current?.stateMachineLoad(${cfgId});
        if (loaded === false) {
          console.error(
            '[Mascot] state machine ' + ${cfgId} + ' failed to load. The animation will ' +
            'autoplay every pose instead of being driven by inputs. Check that the id ' +
            'matches manifest.stateMachines[].id and re-export from Blooby.',
          );
        }
        player.current?.stateMachineStart();
        ready.current = true;
        // defaults live in the .lottie; this replays whatever the app set before load
        apply(pending.current);
      }}
      onStateMachineTransition={(previousState: string, newState: string) => {
        onStateChange?.({
          previousState,
          currentState: newState,
          transition: transitions.find((t) => t.from === previousState && t.to === newState),
        });
      }}
      onStateMachineError={(message: string) => console.warn('[Mascot] state machine:', message)}
    />
  );
});

export default Mascot;
`;
}

const fileBase = (p: Project) => p.name.replace(/\s+/g, '-').toLowerCase() || 'mascot';
/** the one composition every baked state plays — see export/strip.ts */
const animOf = (p: Project) => dotLottieLayout(p).stripId || '(imported)';

function readme(project: Project): string {
  const m = machineOf(project);
  const settable = m.inputs.filter((i) => i.type !== 'Event');
  const example = settable.map((i) => `    ${safeKey(i.name)}: ${JSON.stringify(i.value)},`).join('\n');
  return `# ${project.name} — mascot runtime

Generated by Blooby's State Editor. Three files, all of which belong in your app:

    ${fileBase(project)}.lottie    the animations + the dotLottie state machine
    blooby.machine.json${' '.repeat(Math.max(1, fileBase(project).length - 11))}the same machine, readable — Mascot.tsx reads its input types from here
    Mascot.tsx             the React component

## Install

    npm i @lottiefiles/dotlottie-react-native

Metro does not bundle \`.lottie\` by default. In \`metro.config.js\`:

    config.resolver.assetExts.push('lottie');

## The two names that must match

\`Mascot.tsx\` reads both from \`blooby.machine.json\`, so it stays correct across
re-exports. Import them rather than retyping them — a wrong id fails in silence.

    machine id   ${m.id}          set in the State panel's "Machine" field
    inputs       ${m.inputs.map((i) => i.name).join(', ') || '(none)'}

## Why the poses are one animation

Every state plays \`${animOf(project)}\` and differs only by its \`segment\`, which names a
marker inside it. That is not tidiness: a \`Tweened\` transition interpolates the playhead
*within the loaded composition*, and the engine skips the tween entirely unless both
states name the same animation. Two separate animations can only cut.

So the file is laid out as one strip — pose, morph frames, pose — and a transition scrubs
through the morph. Two things follow:

  * Do not call \`play()\`. It restarts the composition from frame 0 and drops the marker,
    so every pose runs end to end. Use the \`playing\` prop, which freezes instead.
  * Do not set the frame yourself. The machine put the playhead where it is.

## Use

\`\`\`tsx
import { Mascot } from './Mascot';

<Mascot
  inputs={{
${example || '    // no inputs configured yet'}
  }}
  onStateChange={({ previousState, currentState, transition }) => {
    console.log(previousState, '→', currentState, transition?.conditions);
  }}
/>
\`\`\`

You never call \`play('${project.timelines[0]?.name ?? 'idle'}')\`. Set an input; the state
machine evaluates its conditions and changes state itself.

## States

${project.timelines.map((tl) => `- **${tl.name}**${tl.loop ? ' (loops)' : ''}`).join('\n')}

## Inputs

${m.inputs.length
  ? m.inputs.map((i) => `- \`${i.name}\` — ${i.type}${i.type === 'Event' ? '' : `, default \`${JSON.stringify(i.value)}\``} → \`${RUNTIME_SETTER[i.type]}\`${i.description ? ` — ${i.description}` : ''}`).join('\n')
  : '_None configured._'}

## Transitions

${m.transitions.length
  ? machineConfig(project).stateMachine.transitions.map((t) =>
      `- \`${t.from}\` → \`${t.to}\` when ${t.conditions.map((c) => `${c.input} ${c.operator} ${JSON.stringify(c.value)}`).join(` ${t.logic} `)} (${t.duration}s, ${t.easing})`).join('\n')
  : '_None configured — the machine will stay in its initial state._'}

${m.inputs.some((i) => i.type === 'Event') ? `## Events

Event inputs are pulses, not values, so they are fired through the ref:

\`\`\`tsx
const mascot = useRef<MascotHandle>(null);
mascot.current?.fire(${JSON.stringify(m.inputs.find((i) => i.type === 'Event')!.name)});
\`\`\`
` : ''}`;
}

/**
 * Everything an app needs, in one zip: the `.lottie`, the machine config, the component
 * and a README. Downloading a `.lottie` alone left the "now wire it up" half of §7–§11
 * as an exercise, which is where a state machine usually dies.
 */
export function buildRuntimePack(project: Project, opts: Omit<LottieOptions, 'from' | 'to' | 'name'>) {
  const enc = new TextEncoder();
  const bytes = (s: string) => enc.encode(s) as Uint8Array<ArrayBuffer>;
  const { blob, machine } = buildDotLottie(project, opts);
  const base = fileBase(project);

  return blob.arrayBuffer().then((buf) => ({
    machine,
    blob: zipStore([
      { name: `${base}.lottie`, data: new Uint8Array(buf) as Uint8Array<ArrayBuffer> },
      { name: 'blooby.machine.json', data: bytes(JSON.stringify(machineConfig(project), null, 2)) },
      { name: 'Mascot.tsx', data: bytes(mascotSource(project)) },
      { name: 'README.md', data: bytes(readme(project)) },
    ]),
  }));
}
